// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: all-genres.sql

package mangadb

import (
	"context"
)

const getAllGenres = `-- name: GetAllGenres :many
SELECT genre_id, genre_name FROM Genre
`

func (q *Queries) GetAllGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, getAllGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.GenreID, &i.GenreName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
