// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mangadb

import (
	"database/sql"
)

type Author struct {
	AuthorID   int64
	AuthorName string
}

type Demographic struct {
	DemographicID   int64
	DemographicName string
}

type Genre struct {
	GenreID   int64
	GenreName string
}

type Manga struct {
	MangaID         int64
	Title           string
	Subtitle        sql.NullString
	Synopsis        sql.NullString
	Score           sql.NullFloat64
	Members         sql.NullInt64
	CoverImagePath  sql.NullString
	PublicationYear sql.NullInt64
	Type            sql.NullString
	Status          sql.NullString
	TotalVolumes    sql.NullInt64
	TotalChapters   sql.NullInt64
}

type Mangaauthor struct {
	MangaID  int64
	AuthorID int64
	Role     sql.NullString
}

type Mangademographic struct {
	MangaID       int64
	DemographicID int64
}

type Mangagenre struct {
	MangaID int64
	GenreID int64
}

type Mangaserialization struct {
	MangaID         int64
	SerializationID int64
}

type Mangatheme struct {
	MangaID int64
	ThemeID int64
}

type Serialization struct {
	SerializationID   int64
	SerializationName string
}

type Theme struct {
	ThemeID   int64
	ThemeName string
}
