// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mangadb} from '../models';

export function GetAllMangas():Promise<Array<mangadb.GetAllMangaDetailsRow>>;

export function SearchByTitle(arg1:string):Promise<Array<mangadb.SearchMangaByTitleRow>>;
