// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mangadb} from '../models';
import {model} from '../models';

export function GetAllGenres():Promise<Array<mangadb.Genre>>;

export function GetAllMangas():Promise<Array<model.Manga>>;

export function SearchByTitle(arg1:string):Promise<Array<model.Manga>>;
