// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllMangas() {
  return window['go']['main']['App']['GetAllMangas']();
}

export function SearchByTitle(arg1) {
  return window['go']['main']['App']['SearchByTitle'](arg1);
}
